[build]
checksum = "AaTLsynBRAVx-ReFvUbnUm-Cgd_ZoWO-nZeUtyE3VJzsTqIoq6CsCxMVOoMYBnKTBfWXAT7eIEZVAh5oCsTmSaTUSnWV2wnoL4vy6sd4XGCzFkJyOXj0HkuidUpnypjuZFJEhijCPSBu9-yuLZifV6WdLoJFzOqde3_QWxhsT9Tz45fgmgoZkcUA_SIren7_Ze5_-BLf023ZG0ZQ93dZPjXW592YzlmpLiJbNf9TNVT_PLD2pkylEda7N8s"
